version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - dotnet build ArticlesOrganiser.App/ArticlesOrganiser.csproj
  post_build:
    commands:
      - dotnet publish -r linux-x64 ArticlesOrganiser.App/ArticlesOrganiser.csproj
artifacts:  
  files:
    - src/bin/Debug/netcoreapp3.1/linux-x64/publish/**/*
  discard-paths: yes
